syntax = "proto3";

package spaco.account.v1;

service AccountService {
  rpc GetCurrentAccount(GetCurrentAccountRequest) returns (GetCurrentAccountResponse);

  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);
}

message GetCurrentAccountRequest {}

message Account {
  string id = 1;
  optional string atcoder_id = 2;
  string time_zone = 3;
  bool setup_completed = 4;
}

message GetCurrentAccountResponse {
  Account account = 1;
}

message UpdateProfileRequest {
  string atcoder_id = 1;
  string time_zone = 2;
}

message UpdateProfileResponse {
  Account account = 1;
}
