// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogsqlc

import (
	"context"
	"time"
)

const findContestByID = `-- name: FindContestByID :one
SELECT id, title, start_at, duration_seconds, rate_change
FROM contests
WHERE id = $1
`

type FindContestByIDRow struct {
	ID              string
	Title           string
	StartAt         time.Time
	DurationSeconds int64
	RateChange      string
}

func (q *Queries) FindContestByID(ctx context.Context, id string) (FindContestByIDRow, error) {
	row := q.db.QueryRow(ctx, findContestByID, id)
	var i FindContestByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartAt,
		&i.DurationSeconds,
		&i.RateChange,
	)
	return i, err
}

const findProblemByID = `-- name: FindProblemByID :one
SELECT id, contest_id, problem_index, name
FROM problems
WHERE id = $1
`

type FindProblemByIDRow struct {
	ID           string
	ContestID    string
	ProblemIndex *string
	Name         *string
}

func (q *Queries) FindProblemByID(ctx context.Context, id string) (FindProblemByIDRow, error) {
	row := q.db.QueryRow(ctx, findProblemByID, id)
	var i FindProblemByIDRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ProblemIndex,
		&i.Name,
	)
	return i, err
}

const findProblemsByIDs = `-- name: FindProblemsByIDs :many
SELECT id, contest_id, problem_index, name
FROM problems
WHERE id = ANY($1::text[])
`

type FindProblemsByIDsRow struct {
	ID           string
	ContestID    string
	ProblemIndex *string
	Name         *string
}

func (q *Queries) FindProblemsByIDs(ctx context.Context, ids []string) ([]FindProblemsByIDsRow, error) {
	rows, err := q.db.Query(ctx, findProblemsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindProblemsByIDsRow
	for rows.Next() {
		var i FindProblemsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ProblemIndex,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProblemIfNotExists = `-- name: InsertProblemIfNotExists :exec
INSERT INTO problems (id, contest_id)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type InsertProblemIfNotExistsParams struct {
	ID        string
	ContestID string
}

func (q *Queries) InsertProblemIfNotExists(ctx context.Context, arg InsertProblemIfNotExistsParams) error {
	_, err := q.db.Exec(ctx, insertProblemIfNotExists, arg.ID, arg.ContestID)
	return err
}

const listContestProblems = `-- name: ListContestProblems :many
SELECT problem.id, contest_problem.problem_index, problem.name
FROM contest_problems AS contest_problem
JOIN problems AS problem ON problem.id = contest_problem.problem_id
WHERE contest_problem.contest_id = $1
ORDER BY
    char_length(contest_problem.problem_index),
    contest_problem.problem_index,
    problem.id
`

type ListContestProblemsRow struct {
	ID           string
	ProblemIndex string
	Name         *string
}

func (q *Queries) ListContestProblems(ctx context.Context, contestID string) ([]ListContestProblemsRow, error) {
	rows, err := q.db.Query(ctx, listContestProblems, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContestProblemsRow
	for rows.Next() {
		var i ListContestProblemsRow
		if err := rows.Scan(&i.ID, &i.ProblemIndex, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContests = `-- name: SearchContests :many
SELECT id, title, start_at, duration_seconds, rate_change
FROM contests
WHERE lower(id) LIKE $1
   OR regexp_replace(lower(title), '\s', '', 'g') LIKE $1
ORDER BY start_at DESC, id
LIMIT 30
`

type SearchContestsRow struct {
	ID              string
	Title           string
	StartAt         time.Time
	DurationSeconds int64
	RateChange      string
}

func (q *Queries) SearchContests(ctx context.Context, pattern string) ([]SearchContestsRow, error) {
	rows, err := q.db.Query(ctx, searchContests, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContestsRow
	for rows.Next() {
		var i SearchContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartAt,
			&i.DurationSeconds,
			&i.RateChange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContestProblems = `-- name: UpsertContestProblems :exec
INSERT INTO contest_problems (contest_id, problem_id, problem_index)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[])
ON CONFLICT (contest_id, problem_id) DO UPDATE
SET problem_index = EXCLUDED.problem_index
WHERE contest_problems.problem_index IS DISTINCT FROM EXCLUDED.problem_index
`

type UpsertContestProblemsParams struct {
	ContestIds     []string
	ProblemIds     []string
	ProblemIndexes []string
}

func (q *Queries) UpsertContestProblems(ctx context.Context, arg UpsertContestProblemsParams) error {
	_, err := q.db.Exec(ctx, upsertContestProblems, arg.ContestIds, arg.ProblemIds, arg.ProblemIndexes)
	return err
}

const upsertContests = `-- name: UpsertContests :exec
INSERT INTO contests (id, title, start_at, duration_seconds, rate_change)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::timestamptz[]),
    unnest($4::bigint[]),
    unnest($5::text[])
ON CONFLICT (id) DO UPDATE
SET
    title = EXCLUDED.title,
    start_at = EXCLUDED.start_at,
    duration_seconds = EXCLUDED.duration_seconds,
    rate_change = EXCLUDED.rate_change,
    updated_at = now()
WHERE (contests.title, contests.start_at, contests.duration_seconds, contests.rate_change)
    IS DISTINCT FROM (EXCLUDED.title, EXCLUDED.start_at, EXCLUDED.duration_seconds, EXCLUDED.rate_change)
`

type UpsertContestsParams struct {
	Ids              []string
	Titles           []string
	StartAts         []time.Time
	DurationsSeconds []int64
	RateChanges      []string
}

func (q *Queries) UpsertContests(ctx context.Context, arg UpsertContestsParams) error {
	_, err := q.db.Exec(ctx, upsertContests,
		arg.Ids,
		arg.Titles,
		arg.StartAts,
		arg.DurationsSeconds,
		arg.RateChanges,
	)
	return err
}

const upsertProblems = `-- name: UpsertProblems :exec
INSERT INTO problems (id, contest_id, problem_index, name)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::text[])
ON CONFLICT (id) DO UPDATE
SET
    contest_id = EXCLUDED.contest_id,
    problem_index = EXCLUDED.problem_index,
    name = EXCLUDED.name,
    updated_at = now()
WHERE (problems.contest_id, problems.problem_index, problems.name)
    IS DISTINCT FROM (EXCLUDED.contest_id, EXCLUDED.problem_index, EXCLUDED.name)
`

type UpsertProblemsParams struct {
	Ids            []string
	ContestIds     []string
	ProblemIndexes []string
	Names          []string
}

func (q *Queries) UpsertProblems(ctx context.Context, arg UpsertProblemsParams) error {
	_, err := q.db.Exec(ctx, upsertProblems,
		arg.Ids,
		arg.ContestIds,
		arg.ProblemIndexes,
		arg.Names,
	)
	return err
}
