// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogsqlc

import (
	"context"
)

type Querier interface {
	FindContestByID(ctx context.Context, id string) (FindContestByIDRow, error)
	FindProblemByID(ctx context.Context, id string) (FindProblemByIDRow, error)
	FindProblemsByIDs(ctx context.Context, ids []string) ([]FindProblemsByIDsRow, error)
	InsertProblemIfNotExists(ctx context.Context, arg InsertProblemIfNotExistsParams) error
	ListContestProblems(ctx context.Context, contestID string) ([]ListContestProblemsRow, error)
	SearchContests(ctx context.Context, pattern string) ([]SearchContestsRow, error)
	UpsertContestProblems(ctx context.Context, arg UpsertContestProblemsParams) error
	UpsertContests(ctx context.Context, arg UpsertContestsParams) error
	UpsertProblems(ctx context.Context, arg UpsertProblemsParams) error
}

var _ Querier = (*Queries)(nil)
