// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reviewsqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ReviewItem struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	ProblemID        string
	RegistrationNote string
	RegisteredAt     time.Time
	PausedAt         *time.Time
	State            string
	DueOn            pgtype.Date
	IntervalDays     int32
	Stability        *float64
	Difficulty       *float64
	Reps             int32
	Lapses           int32
	LastReviewedAt   *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ReviewLog struct {
	ID               uuid.UUID
	ReviewItemID     uuid.UUID
	UserID           uuid.UUID
	RequestID        uuid.UUID
	Result           string
	Rating           int16
	PerformedAt      time.Time
	Note             string
	StateBefore      string
	ElapsedDays      int32
	LastIntervalDays int32
	IntervalDays     int32
	Stability        float64
	Difficulty       float64
	NextDueOn        pgtype.Date
	CreatedAt        time.Time
}
