// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reviewsqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountReviewLogsPerformedBetween(ctx context.Context, arg CountReviewLogsPerformedBetweenParams) (int64, error)
	// pgxのexec modeは[]uuid.UUIDを配列として送れないため、UUIDの配列はtextで受け取って変換する。
	CreateReviewItems(ctx context.Context, arg CreateReviewItemsParams) ([]ReviewItem, error)
	CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (ReviewLog, error)
	FindLatestReviewLogs(ctx context.Context, arg FindLatestReviewLogsParams) ([]ReviewLog, error)
	FindReviewItemByID(ctx context.Context, arg FindReviewItemByIDParams) (ReviewItem, error)
	FindReviewItemsByProblemIDs(ctx context.Context, arg FindReviewItemsByProblemIDsParams) ([]ReviewItem, error)
	FindReviewLogByRequestID(ctx context.Context, arg FindReviewLogByRequestIDParams) (ReviewLog, error)
	ListDueReviewItems(ctx context.Context, arg ListDueReviewItemsParams) ([]ReviewItem, error)
	ListRegisteredProblemIDs(ctx context.Context, arg ListRegisteredProblemIDsParams) ([]string, error)
	ListReviewItems(ctx context.Context, userID uuid.UUID) ([]ReviewItem, error)
	ListReviewLogs(ctx context.Context, userID uuid.UUID) ([]ReviewLog, error)
	ListUpcomingReviewItems(ctx context.Context, arg ListUpcomingReviewItemsParams) ([]ReviewItem, error)
	LockReviewItemByID(ctx context.Context, arg LockReviewItemByIDParams) (ReviewItem, error)
	UpdateReviewItemPausedAt(ctx context.Context, arg UpdateReviewItemPausedAtParams) (ReviewItem, error)
	UpdateReviewItemSchedule(ctx context.Context, arg UpdateReviewItemScheduleParams) (ReviewItem, error)
}

var _ Querier = (*Queries)(nil)
