// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package reviewsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReviewLogsPerformedBetween = `-- name: CountReviewLogsPerformedBetween :one
SELECT count(*)
FROM review_logs
WHERE user_id = $1
  AND performed_at >= $2
  AND performed_at < $3
`

type CountReviewLogsPerformedBetweenParams struct {
	UserID         uuid.UUID
	PerformedFrom  time.Time
	PerformedUntil time.Time
}

func (q *Queries) CountReviewLogsPerformedBetween(ctx context.Context, arg CountReviewLogsPerformedBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewLogsPerformedBetween, arg.UserID, arg.PerformedFrom, arg.PerformedUntil)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReviewItems = `-- name: CreateReviewItems :many
INSERT INTO review_items (id, user_id, problem_id, registration_note, registered_at, due_on)
SELECT
    unnest($1::text[])::uuid,
    unnest($2::text[])::uuid,
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::timestamptz[]),
    unnest($6::date[])
ON CONFLICT (user_id, problem_id) DO NOTHING
RETURNING id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
`

type CreateReviewItemsParams struct {
	Ids               []string
	UserIds           []string
	ProblemIds        []string
	RegistrationNotes []string
	RegisteredAts     []time.Time
	DueOns            []pgtype.Date
}

// pgxのexec modeは[]uuid.UUIDを配列として送れないため、UUIDの配列はtextで受け取って変換する。
func (q *Queries) CreateReviewItems(ctx context.Context, arg CreateReviewItemsParams) ([]ReviewItem, error) {
	rows, err := q.db.Query(ctx, createReviewItems,
		arg.Ids,
		arg.UserIds,
		arg.ProblemIds,
		arg.RegistrationNotes,
		arg.RegisteredAts,
		arg.DueOns,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewItem
	for rows.Next() {
		var i ReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.RegistrationNote,
			&i.RegisteredAt,
			&i.PausedAt,
			&i.State,
			&i.DueOn,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.LastReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReviewLog = `-- name: CreateReviewLog :one
INSERT INTO review_logs (
    id,
    review_item_id,
    user_id,
    request_id,
    result,
    rating,
    performed_at,
    note,
    state_before,
    elapsed_days,
    last_interval_days,
    interval_days,
    stability,
    difficulty,
    next_due_on
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING id, review_item_id, user_id, request_id, result, rating, performed_at, note, state_before, elapsed_days, last_interval_days, interval_days, stability, difficulty, next_due_on, created_at
`

type CreateReviewLogParams struct {
	ID               uuid.UUID
	ReviewItemID     uuid.UUID
	UserID           uuid.UUID
	RequestID        uuid.UUID
	Result           string
	Rating           int16
	PerformedAt      time.Time
	Note             string
	StateBefore      string
	ElapsedDays      int32
	LastIntervalDays int32
	IntervalDays     int32
	Stability        float64
	Difficulty       float64
	NextDueOn        pgtype.Date
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) (ReviewLog, error) {
	row := q.db.QueryRow(ctx, createReviewLog,
		arg.ID,
		arg.ReviewItemID,
		arg.UserID,
		arg.RequestID,
		arg.Result,
		arg.Rating,
		arg.PerformedAt,
		arg.Note,
		arg.StateBefore,
		arg.ElapsedDays,
		arg.LastIntervalDays,
		arg.IntervalDays,
		arg.Stability,
		arg.Difficulty,
		arg.NextDueOn,
	)
	var i ReviewLog
	err := row.Scan(
		&i.ID,
		&i.ReviewItemID,
		&i.UserID,
		&i.RequestID,
		&i.Result,
		&i.Rating,
		&i.PerformedAt,
		&i.Note,
		&i.StateBefore,
		&i.ElapsedDays,
		&i.LastIntervalDays,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.NextDueOn,
		&i.CreatedAt,
	)
	return i, err
}

const findLatestReviewLogs = `-- name: FindLatestReviewLogs :many
SELECT DISTINCT ON (review_item_id) id, review_item_id, user_id, request_id, result, rating, performed_at, note, state_before, elapsed_days, last_interval_days, interval_days, stability, difficulty, next_due_on, created_at
FROM review_logs
WHERE user_id = $1
  AND review_item_id = ANY($2::text[]::uuid[])
ORDER BY review_item_id, performed_at DESC, created_at DESC
`

type FindLatestReviewLogsParams struct {
	UserID        uuid.UUID
	ReviewItemIds []string
}

func (q *Queries) FindLatestReviewLogs(ctx context.Context, arg FindLatestReviewLogsParams) ([]ReviewLog, error) {
	rows, err := q.db.Query(ctx, findLatestReviewLogs, arg.UserID, arg.ReviewItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewLog
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.ReviewItemID,
			&i.UserID,
			&i.RequestID,
			&i.Result,
			&i.Rating,
			&i.PerformedAt,
			&i.Note,
			&i.StateBefore,
			&i.ElapsedDays,
			&i.LastIntervalDays,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.NextDueOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReviewItemByID = `-- name: FindReviewItemByID :one
SELECT id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
FROM review_items
WHERE user_id = $1 AND id = $2
`

type FindReviewItemByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) FindReviewItemByID(ctx context.Context, arg FindReviewItemByIDParams) (ReviewItem, error) {
	row := q.db.QueryRow(ctx, findReviewItemByID, arg.UserID, arg.ID)
	var i ReviewItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.RegistrationNote,
		&i.RegisteredAt,
		&i.PausedAt,
		&i.State,
		&i.DueOn,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findReviewItemsByProblemIDs = `-- name: FindReviewItemsByProblemIDs :many
SELECT id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
FROM review_items
WHERE user_id = $1
  AND problem_id = ANY($2::text[])
`

type FindReviewItemsByProblemIDsParams struct {
	UserID     uuid.UUID
	ProblemIds []string
}

func (q *Queries) FindReviewItemsByProblemIDs(ctx context.Context, arg FindReviewItemsByProblemIDsParams) ([]ReviewItem, error) {
	rows, err := q.db.Query(ctx, findReviewItemsByProblemIDs, arg.UserID, arg.ProblemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewItem
	for rows.Next() {
		var i ReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.RegistrationNote,
			&i.RegisteredAt,
			&i.PausedAt,
			&i.State,
			&i.DueOn,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.LastReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReviewLogByRequestID = `-- name: FindReviewLogByRequestID :one
SELECT id, review_item_id, user_id, request_id, result, rating, performed_at, note, state_before, elapsed_days, last_interval_days, interval_days, stability, difficulty, next_due_on, created_at
FROM review_logs
WHERE user_id = $1 AND request_id = $2
`

type FindReviewLogByRequestIDParams struct {
	UserID    uuid.UUID
	RequestID uuid.UUID
}

func (q *Queries) FindReviewLogByRequestID(ctx context.Context, arg FindReviewLogByRequestIDParams) (ReviewLog, error) {
	row := q.db.QueryRow(ctx, findReviewLogByRequestID, arg.UserID, arg.RequestID)
	var i ReviewLog
	err := row.Scan(
		&i.ID,
		&i.ReviewItemID,
		&i.UserID,
		&i.RequestID,
		&i.Result,
		&i.Rating,
		&i.PerformedAt,
		&i.Note,
		&i.StateBefore,
		&i.ElapsedDays,
		&i.LastIntervalDays,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.NextDueOn,
		&i.CreatedAt,
	)
	return i, err
}

const listDueReviewItems = `-- name: ListDueReviewItems :many
SELECT id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
FROM review_items
WHERE user_id = $1
  AND paused_at IS NULL
  AND due_on <= $2
ORDER BY due_on, registered_at, id
`

type ListDueReviewItemsParams struct {
	UserID uuid.UUID
	Today  pgtype.Date
}

func (q *Queries) ListDueReviewItems(ctx context.Context, arg ListDueReviewItemsParams) ([]ReviewItem, error) {
	rows, err := q.db.Query(ctx, listDueReviewItems, arg.UserID, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewItem
	for rows.Next() {
		var i ReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.RegistrationNote,
			&i.RegisteredAt,
			&i.PausedAt,
			&i.State,
			&i.DueOn,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.LastReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegisteredProblemIDs = `-- name: ListRegisteredProblemIDs :many
SELECT problem_id
FROM review_items
WHERE user_id = $1
  AND problem_id = ANY($2::text[])
ORDER BY problem_id
`

type ListRegisteredProblemIDsParams struct {
	UserID     uuid.UUID
	ProblemIds []string
}

func (q *Queries) ListRegisteredProblemIDs(ctx context.Context, arg ListRegisteredProblemIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRegisteredProblemIDs, arg.UserID, arg.ProblemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var problem_id string
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewItems = `-- name: ListReviewItems :many
SELECT id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
FROM review_items
WHERE user_id = $1
ORDER BY registered_at DESC, id DESC
`

func (q *Queries) ListReviewItems(ctx context.Context, userID uuid.UUID) ([]ReviewItem, error) {
	rows, err := q.db.Query(ctx, listReviewItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewItem
	for rows.Next() {
		var i ReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.RegistrationNote,
			&i.RegisteredAt,
			&i.PausedAt,
			&i.State,
			&i.DueOn,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.LastReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewLogs = `-- name: ListReviewLogs :many
SELECT id, review_item_id, user_id, request_id, result, rating, performed_at, note, state_before, elapsed_days, last_interval_days, interval_days, stability, difficulty, next_due_on, created_at
FROM review_logs
WHERE user_id = $1
ORDER BY performed_at, created_at
`

func (q *Queries) ListReviewLogs(ctx context.Context, userID uuid.UUID) ([]ReviewLog, error) {
	rows, err := q.db.Query(ctx, listReviewLogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewLog
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.ReviewItemID,
			&i.UserID,
			&i.RequestID,
			&i.Result,
			&i.Rating,
			&i.PerformedAt,
			&i.Note,
			&i.StateBefore,
			&i.ElapsedDays,
			&i.LastIntervalDays,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.NextDueOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingReviewItems = `-- name: ListUpcomingReviewItems :many
SELECT id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
FROM review_items
WHERE user_id = $1
  AND paused_at IS NULL
  AND due_on > $2
ORDER BY due_on, registered_at, id
LIMIT $3
`

type ListUpcomingReviewItemsParams struct {
	UserID   uuid.UUID
	Today    pgtype.Date
	MaxItems int32
}

func (q *Queries) ListUpcomingReviewItems(ctx context.Context, arg ListUpcomingReviewItemsParams) ([]ReviewItem, error) {
	rows, err := q.db.Query(ctx, listUpcomingReviewItems, arg.UserID, arg.Today, arg.MaxItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewItem
	for rows.Next() {
		var i ReviewItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProblemID,
			&i.RegistrationNote,
			&i.RegisteredAt,
			&i.PausedAt,
			&i.State,
			&i.DueOn,
			&i.IntervalDays,
			&i.Stability,
			&i.Difficulty,
			&i.Reps,
			&i.Lapses,
			&i.LastReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReviewItemByID = `-- name: LockReviewItemByID :one
SELECT id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
FROM review_items
WHERE user_id = $1 AND id = $2
FOR UPDATE
`

type LockReviewItemByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) LockReviewItemByID(ctx context.Context, arg LockReviewItemByIDParams) (ReviewItem, error) {
	row := q.db.QueryRow(ctx, lockReviewItemByID, arg.UserID, arg.ID)
	var i ReviewItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.RegistrationNote,
		&i.RegisteredAt,
		&i.PausedAt,
		&i.State,
		&i.DueOn,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewItemPausedAt = `-- name: UpdateReviewItemPausedAt :one
UPDATE review_items
SET
    paused_at = $1,
    updated_at = now()
WHERE user_id = $2 AND id = $3
RETURNING id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
`

type UpdateReviewItemPausedAtParams struct {
	PausedAt *time.Time
	UserID   uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) UpdateReviewItemPausedAt(ctx context.Context, arg UpdateReviewItemPausedAtParams) (ReviewItem, error) {
	row := q.db.QueryRow(ctx, updateReviewItemPausedAt, arg.PausedAt, arg.UserID, arg.ID)
	var i ReviewItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.RegistrationNote,
		&i.RegisteredAt,
		&i.PausedAt,
		&i.State,
		&i.DueOn,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewItemSchedule = `-- name: UpdateReviewItemSchedule :one
UPDATE review_items
SET
    state = $1,
    due_on = $2,
    interval_days = $3,
    stability = $4,
    difficulty = $5,
    reps = $6,
    lapses = $7,
    last_reviewed_at = $8,
    updated_at = now()
WHERE user_id = $9 AND id = $10
RETURNING id, user_id, problem_id, registration_note, registered_at, paused_at, state, due_on, interval_days, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
`

type UpdateReviewItemScheduleParams struct {
	State          string
	DueOn          pgtype.Date
	IntervalDays   int32
	Stability      *float64
	Difficulty     *float64
	Reps           int32
	Lapses         int32
	LastReviewedAt *time.Time
	UserID         uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) UpdateReviewItemSchedule(ctx context.Context, arg UpdateReviewItemScheduleParams) (ReviewItem, error) {
	row := q.db.QueryRow(ctx, updateReviewItemSchedule,
		arg.State,
		arg.DueOn,
		arg.IntervalDays,
		arg.Stability,
		arg.Difficulty,
		arg.Reps,
		arg.Lapses,
		arg.LastReviewedAt,
		arg.UserID,
		arg.ID,
	)
	var i ReviewItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProblemID,
		&i.RegistrationNote,
		&i.RegisteredAt,
		&i.PausedAt,
		&i.State,
		&i.DueOn,
		&i.IntervalDays,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
