// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file spaco/account/v1/account.proto (package spaco.account.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spaco/account/v1/account.proto.
 */
export const file_spaco_account_v1_account: GenFile /*@__PURE__*/ = fileDesc(
  "Ch5zcGFjby9hY2NvdW50L3YxL2FjY291bnQucHJvdG8SEHNwYWNvLmFjY291bnQudjEiGgoYR2V0Q3VycmVudEFjY291bnRSZXF1ZXN0ImkKB0FjY291bnQSCgoCaWQYASABKAkSFwoKYXRjb2Rlcl9pZBgCIAEoCUgAiAEBEhEKCXRpbWVfem9uZRgDIAEoCRIXCg9zZXR1cF9jb21wbGV0ZWQYBCABKAhCDQoLX2F0Y29kZXJfaWQiRwoZR2V0Q3VycmVudEFjY291bnRSZXNwb25zZRIqCgdhY2NvdW50GAEgASgLMhkuc3BhY28uYWNjb3VudC52MS5BY2NvdW50Ij0KFFVwZGF0ZVByb2ZpbGVSZXF1ZXN0EhIKCmF0Y29kZXJfaWQYASABKAkSEQoJdGltZV96b25lGAIgASgJIkMKFVVwZGF0ZVByb2ZpbGVSZXNwb25zZRIqCgdhY2NvdW50GAEgASgLMhkuc3BhY28uYWNjb3VudC52MS5BY2NvdW50MuABCg5BY2NvdW50U2VydmljZRJsChFHZXRDdXJyZW50QWNjb3VudBIqLnNwYWNvLmFjY291bnQudjEuR2V0Q3VycmVudEFjY291bnRSZXF1ZXN0Gisuc3BhY28uYWNjb3VudC52MS5HZXRDdXJyZW50QWNjb3VudFJlc3BvbnNlEmAKDVVwZGF0ZVByb2ZpbGUSJi5zcGFjby5hY2NvdW50LnYxLlVwZGF0ZVByb2ZpbGVSZXF1ZXN0Gicuc3BhY28uYWNjb3VudC52MS5VcGRhdGVQcm9maWxlUmVzcG9uc2VCzQEKFGNvbS5zcGFjby5hY2NvdW50LnYxQgxBY2NvdW50UHJvdG9QAVpFZ2l0aHViLmNvbS9nZXNvcDBuL3NwYWNvL2JhY2tlbmQvZ2VuZXJhdGVkL3NwYWNvL2FjY291bnQvdjE7YWNjb3VudHYxogIDU0FYqgIQU3BhY28uQWNjb3VudC5WMcoCEFNwYWNvXEFjY291bnRcVjHiAhxTcGFjb1xBY2NvdW50XFYxXEdQQk1ldGFkYXRh6gISU3BhY286OkFjY291bnQ6OlYxYgZwcm90bzM",
);

/**
 * @generated from message spaco.account.v1.GetCurrentAccountRequest
 */
export type GetCurrentAccountRequest = Message<"spaco.account.v1.GetCurrentAccountRequest"> & {};

/**
 * Describes the message spaco.account.v1.GetCurrentAccountRequest.
 * Use `create(GetCurrentAccountRequestSchema)` to create a new message.
 */
export const GetCurrentAccountRequestSchema: GenMessage<GetCurrentAccountRequest> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 0);

/**
 * @generated from message spaco.account.v1.Account
 */
export type Account = Message<"spaco.account.v1.Account"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string atcoder_id = 2;
   */
  atcoderId?: string | undefined;

  /**
   * @generated from field: string time_zone = 3;
   */
  timeZone: string;

  /**
   * @generated from field: bool setup_completed = 4;
   */
  setupCompleted: boolean;
};

/**
 * Describes the message spaco.account.v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> /*@__PURE__*/ = messageDesc(
  file_spaco_account_v1_account,
  1,
);

/**
 * @generated from message spaco.account.v1.GetCurrentAccountResponse
 */
export type GetCurrentAccountResponse = Message<"spaco.account.v1.GetCurrentAccountResponse"> & {
  /**
   * @generated from field: spaco.account.v1.Account account = 1;
   */
  account?: Account | undefined;
};

/**
 * Describes the message spaco.account.v1.GetCurrentAccountResponse.
 * Use `create(GetCurrentAccountResponseSchema)` to create a new message.
 */
export const GetCurrentAccountResponseSchema: GenMessage<GetCurrentAccountResponse> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 2);

/**
 * @generated from message spaco.account.v1.UpdateProfileRequest
 */
export type UpdateProfileRequest = Message<"spaco.account.v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: string atcoder_id = 1;
   */
  atcoderId: string;

  /**
   * @generated from field: string time_zone = 2;
   */
  timeZone: string;
};

/**
 * Describes the message spaco.account.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 3);

/**
 * @generated from message spaco.account.v1.UpdateProfileResponse
 */
export type UpdateProfileResponse = Message<"spaco.account.v1.UpdateProfileResponse"> & {
  /**
   * @generated from field: spaco.account.v1.Account account = 1;
   */
  account?: Account | undefined;
};

/**
 * Describes the message spaco.account.v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 4);

/**
 * @generated from service spaco.account.v1.AccountService
 */
export const AccountService: GenService<{
  /**
   * @generated from rpc spaco.account.v1.AccountService.GetCurrentAccount
   */
  getCurrentAccount: {
    methodKind: "unary";
    input: typeof GetCurrentAccountRequestSchema;
    output: typeof GetCurrentAccountResponseSchema;
  };
  /**
   * @generated from rpc spaco.account.v1.AccountService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UpdateProfileResponseSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_spaco_account_v1_account, 0);
