// @generated by protoc-gen-es v2.14.0 with parameter "target=ts"
// @generated from file spaco/account/v1/account.proto (package spaco.account.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spaco/account/v1/account.proto.
 */
export const file_spaco_account_v1_account: GenFile /*@__PURE__*/ = fileDesc(
  "Ch5zcGFjby9hY2NvdW50L3YxL2FjY291bnQucHJvdG8SEHNwYWNvLmFjY291bnQudjEiGgoYR2V0Q3VycmVudEFjY291bnRSZXF1ZXN0IpwBCgdBY2NvdW50EgoKAmlkGAEgASgJEhcKCmF0Y29kZXJfaWQYAiABKAlIAIgBARIRCgl0aW1lX3pvbmUYAyABKAkSFwoPc2V0dXBfY29tcGxldGVkGAQgASgIEhUKCHVzZXJuYW1lGAUgASgJSAGIAQESDQoFZW1haWwYBiABKAlCDQoLX2F0Y29kZXJfaWRCCwoJX3VzZXJuYW1lIkcKGUdldEN1cnJlbnRBY2NvdW50UmVzcG9uc2USKgoHYWNjb3VudBgBIAEoCzIZLnNwYWNvLmFjY291bnQudjEuQWNjb3VudCJPChRVcGRhdGVQcm9maWxlUmVxdWVzdBISCgphdGNvZGVyX2lkGAEgASgJEhEKCXRpbWVfem9uZRgCIAEoCRIQCgh1c2VybmFtZRgDIAEoCSJDChVVcGRhdGVQcm9maWxlUmVzcG9uc2USKgoHYWNjb3VudBgBIAEoCzIZLnNwYWNvLmFjY291bnQudjEuQWNjb3VudDLgAQoOQWNjb3VudFNlcnZpY2USbAoRR2V0Q3VycmVudEFjY291bnQSKi5zcGFjby5hY2NvdW50LnYxLkdldEN1cnJlbnRBY2NvdW50UmVxdWVzdBorLnNwYWNvLmFjY291bnQudjEuR2V0Q3VycmVudEFjY291bnRSZXNwb25zZRJgCg1VcGRhdGVQcm9maWxlEiYuc3BhY28uYWNjb3VudC52MS5VcGRhdGVQcm9maWxlUmVxdWVzdBonLnNwYWNvLmFjY291bnQudjEuVXBkYXRlUHJvZmlsZVJlc3BvbnNlQs0BChRjb20uc3BhY28uYWNjb3VudC52MUIMQWNjb3VudFByb3RvUAFaRWdpdGh1Yi5jb20vZ2Vzb3Awbi9zcGFjby9iYWNrZW5kL2dlbmVyYXRlZC9zcGFjby9hY2NvdW50L3YxO2FjY291bnR2MaICA1NBWKoCEFNwYWNvLkFjY291bnQuVjHKAhBTcGFjb1xBY2NvdW50XFYx4gIcU3BhY29cQWNjb3VudFxWMVxHUEJNZXRhZGF0YeoCElNwYWNvOjpBY2NvdW50OjpWMWIGcHJvdG8z",
);

/**
 * @generated from message spaco.account.v1.GetCurrentAccountRequest
 */
export type GetCurrentAccountRequest = Message<"spaco.account.v1.GetCurrentAccountRequest"> & {};

/**
 * Describes the message spaco.account.v1.GetCurrentAccountRequest.
 * Use `create(GetCurrentAccountRequestSchema)` to create a new message.
 */
export const GetCurrentAccountRequestSchema: GenMessage<GetCurrentAccountRequest> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 0);

/**
 * @generated from message spaco.account.v1.Account
 */
export type Account = Message<"spaco.account.v1.Account"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string atcoder_id = 2;
   */
  atcoderId?: string | undefined;

  /**
   * @generated from field: string time_zone = 3;
   */
  timeZone: string;

  /**
   * @generated from field: bool setup_completed = 4;
   */
  setupCompleted: boolean;

  /**
   * アプリ内の表示名。初期設定前は未設定。
   *
   * @generated from field: optional string username = 5;
   */
  username?: string | undefined;

  /**
   * 認証時に確定し、プロフィールからは変更しないメールアドレス。
   *
   * @generated from field: string email = 6;
   */
  email: string;
};

/**
 * Describes the message spaco.account.v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> /*@__PURE__*/ = messageDesc(
  file_spaco_account_v1_account,
  1,
);

/**
 * @generated from message spaco.account.v1.GetCurrentAccountResponse
 */
export type GetCurrentAccountResponse = Message<"spaco.account.v1.GetCurrentAccountResponse"> & {
  /**
   * @generated from field: spaco.account.v1.Account account = 1;
   */
  account?: Account | undefined;
};

/**
 * Describes the message spaco.account.v1.GetCurrentAccountResponse.
 * Use `create(GetCurrentAccountResponseSchema)` to create a new message.
 */
export const GetCurrentAccountResponseSchema: GenMessage<GetCurrentAccountResponse> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 2);

/**
 * @generated from message spaco.account.v1.UpdateProfileRequest
 */
export type UpdateProfileRequest = Message<"spaco.account.v1.UpdateProfileRequest"> & {
  /**
   * 空文字または省略で、登録済みのAtCoder IDも解除する。
   *
   * @generated from field: string atcoder_id = 1;
   */
  atcoderId: string;

  /**
   * @generated from field: string time_zone = 2;
   */
  timeZone: string;

  /**
   * 必須の表示名。前後の空白を除き1〜40文字。重複は許可する。
   *
   * @generated from field: string username = 3;
   */
  username: string;
};

/**
 * Describes the message spaco.account.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 3);

/**
 * @generated from message spaco.account.v1.UpdateProfileResponse
 */
export type UpdateProfileResponse = Message<"spaco.account.v1.UpdateProfileResponse"> & {
  /**
   * @generated from field: spaco.account.v1.Account account = 1;
   */
  account?: Account | undefined;
};

/**
 * Describes the message spaco.account.v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse> /*@__PURE__*/ =
  messageDesc(file_spaco_account_v1_account, 4);

/**
 * @generated from service spaco.account.v1.AccountService
 */
export const AccountService: GenService<{
  /**
   * @generated from rpc spaco.account.v1.AccountService.GetCurrentAccount
   */
  getCurrentAccount: {
    methodKind: "unary";
    input: typeof GetCurrentAccountRequestSchema;
    output: typeof GetCurrentAccountResponseSchema;
  };
  /**
   * @generated from rpc spaco.account.v1.AccountService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UpdateProfileResponseSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_spaco_account_v1_account, 0);
