// @generated by protoc-gen-es v2.14.0 with parameter "target=ts,erasable_syntax=true"
// @generated from file spaco/catalog/v1/catalog.proto (package spaco.catalog.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spaco/catalog/v1/catalog.proto.
 */
export const file_spaco_catalog_v1_catalog: GenFile /*@__PURE__*/ = fileDesc(
  "Ch5zcGFjby9jYXRhbG9nL3YxL2NhdGFsb2cucHJvdG8SEHNwYWNvLmNhdGFsb2cudjEiUgoHQ29udGVzdBIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRIsCghzdGFydF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAigAEKB1Byb2JsZW0SCgoCaWQYASABKAkSEgoKY29udGVzdF9pZBgCIAEoCRIaCg1wcm9ibGVtX2luZGV4GAMgASgJSACIAQESEQoEbmFtZRgEIAEoCUgBiAEBEgsKA3VybBgFIAEoCUIQCg5fcHJvYmxlbV9pbmRleEIHCgVfbmFtZSImChVTZWFyY2hDb250ZXN0c1JlcXVlc3QSDQoFcXVlcnkYASABKAkiRQoWU2VhcmNoQ29udGVzdHNSZXNwb25zZRIrCghjb250ZXN0cxgBIAMoCzIZLnNwYWNvLmNhdGFsb2cudjEuQ29udGVzdCIwChpMaXN0Q29udGVzdFByb2JsZW1zUmVxdWVzdBISCgpjb250ZXN0X2lkGAEgASgJInYKG0xpc3RDb250ZXN0UHJvYmxlbXNSZXNwb25zZRIqCgdjb250ZXN0GAEgASgLMhkuc3BhY28uY2F0YWxvZy52MS5Db250ZXN0EisKCHByb2JsZW1zGAIgAygLMhkuc3BhY28uY2F0YWxvZy52MS5Qcm9ibGVtMukBCg5DYXRhbG9nU2VydmljZRJjCg5TZWFyY2hDb250ZXN0cxInLnNwYWNvLmNhdGFsb2cudjEuU2VhcmNoQ29udGVzdHNSZXF1ZXN0Giguc3BhY28uY2F0YWxvZy52MS5TZWFyY2hDb250ZXN0c1Jlc3BvbnNlEnIKE0xpc3RDb250ZXN0UHJvYmxlbXMSLC5zcGFjby5jYXRhbG9nLnYxLkxpc3RDb250ZXN0UHJvYmxlbXNSZXF1ZXN0Gi0uc3BhY28uY2F0YWxvZy52MS5MaXN0Q29udGVzdFByb2JsZW1zUmVzcG9uc2VCzQEKFGNvbS5zcGFjby5jYXRhbG9nLnYxQgxDYXRhbG9nUHJvdG9QAVpFZ2l0aHViLmNvbS9nZXNvcDBuL3NwYWNvL2JhY2tlbmQvZ2VuZXJhdGVkL3NwYWNvL2NhdGFsb2cvdjE7Y2F0YWxvZ3YxogIDU0NYqgIQU3BhY28uQ2F0YWxvZy5WMcoCEFNwYWNvXENhdGFsb2dcVjHiAhxTcGFjb1xDYXRhbG9nXFYxXEdQQk1ldGFkYXRh6gISU3BhY286OkNhdGFsb2c6OlYxYgZwcm90bzM",
  [file_google_protobuf_timestamp],
);

/**
 * @generated from message spaco.catalog.v1.Contest
 */
export type Contest = Message<"spaco.catalog.v1.Contest"> & {
  /**
   * 例: abc350
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: google.protobuf.Timestamp start_at = 3;
   */
  startAt?: Timestamp | undefined;
};

/**
 * Describes the message spaco.catalog.v1.Contest.
 * Use `create(ContestSchema)` to create a new message.
 */
export const ContestSchema: GenMessage<Contest> /*@__PURE__*/ = messageDesc(
  file_spaco_catalog_v1_catalog,
  0,
);

/**
 * @generated from message spaco.catalog.v1.Problem
 */
export type Problem = Message<"spaco.catalog.v1.Problem"> & {
  /**
   * 例: abc350_d
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 表示と問題URLに使うコンテストID。
   *
   * @generated from field: string contest_id = 2;
   */
  contestId: string;

  /**
   * 例: D。問題URLから登録し、まだ補完していない問題では未設定。
   *
   * @generated from field: optional string problem_index = 3;
   */
  problemIndex?: string | undefined;

  /**
   * 問題URLから登録し、まだ補完していない問題では未設定。
   *
   * @generated from field: optional string name = 4;
   */
  name?: string | undefined;

  /**
   * AtCoderの問題ページのURL。
   *
   * @generated from field: string url = 5;
   */
  url: string;
};

/**
 * Describes the message spaco.catalog.v1.Problem.
 * Use `create(ProblemSchema)` to create a new message.
 */
export const ProblemSchema: GenMessage<Problem> /*@__PURE__*/ = messageDesc(
  file_spaco_catalog_v1_catalog,
  1,
);

/**
 * @generated from message spaco.catalog.v1.SearchContestsRequest
 */
export type SearchContestsRequest = Message<"spaco.catalog.v1.SearchContestsRequest"> & {
  /**
   * 空白と大文字・小文字の違いは無視する。例: "ABC 350"
   *
   * @generated from field: string query = 1;
   */
  query: string;
};

/**
 * Describes the message spaco.catalog.v1.SearchContestsRequest.
 * Use `create(SearchContestsRequestSchema)` to create a new message.
 */
export const SearchContestsRequestSchema: GenMessage<SearchContestsRequest> /*@__PURE__*/ =
  messageDesc(file_spaco_catalog_v1_catalog, 2);

/**
 * @generated from message spaco.catalog.v1.SearchContestsResponse
 */
export type SearchContestsResponse = Message<"spaco.catalog.v1.SearchContestsResponse"> & {
  /**
   * 最大30件。
   *
   * @generated from field: repeated spaco.catalog.v1.Contest contests = 1;
   */
  contests: Contest[];
};

/**
 * Describes the message spaco.catalog.v1.SearchContestsResponse.
 * Use `create(SearchContestsResponseSchema)` to create a new message.
 */
export const SearchContestsResponseSchema: GenMessage<SearchContestsResponse> /*@__PURE__*/ =
  messageDesc(file_spaco_catalog_v1_catalog, 3);

/**
 * @generated from message spaco.catalog.v1.ListContestProblemsRequest
 */
export type ListContestProblemsRequest = Message<"spaco.catalog.v1.ListContestProblemsRequest"> & {
  /**
   * @generated from field: string contest_id = 1;
   */
  contestId: string;
};

/**
 * Describes the message spaco.catalog.v1.ListContestProblemsRequest.
 * Use `create(ListContestProblemsRequestSchema)` to create a new message.
 */
export const ListContestProblemsRequestSchema: GenMessage<ListContestProblemsRequest> /*@__PURE__*/ =
  messageDesc(file_spaco_catalog_v1_catalog, 4);

/**
 * @generated from message spaco.catalog.v1.ListContestProblemsResponse
 */
export type ListContestProblemsResponse =
  Message<"spaco.catalog.v1.ListContestProblemsResponse"> & {
    /**
     * @generated from field: spaco.catalog.v1.Contest contest = 1;
     */
    contest?: Contest | undefined;

    /**
     * @generated from field: repeated spaco.catalog.v1.Problem problems = 2;
     */
    problems: Problem[];
  };

/**
 * Describes the message spaco.catalog.v1.ListContestProblemsResponse.
 * Use `create(ListContestProblemsResponseSchema)` to create a new message.
 */
export const ListContestProblemsResponseSchema: GenMessage<ListContestProblemsResponse> /*@__PURE__*/ =
  messageDesc(file_spaco_catalog_v1_catalog, 5);

/**
 * AtCoder Problemsから取り込んだコンテストと問題を検索する。
 *
 * @generated from service spaco.catalog.v1.CatalogService
 */
export const CatalogService: GenService<{
  /**
   * コンテストIDまたはコンテスト名で検索する。空文字では開始日時が新しい順に返す。
   *
   * @generated from rpc spaco.catalog.v1.CatalogService.SearchContests
   */
  searchContests: {
    methodKind: "unary";
    input: typeof SearchContestsRequestSchema;
    output: typeof SearchContestsResponseSchema;
  };
  /**
   * コンテストに含まれる問題を、問題番号順に返す。
   *
   * @generated from rpc spaco.catalog.v1.CatalogService.ListContestProblems
   */
  listContestProblems: {
    methodKind: "unary";
    input: typeof ListContestProblemsRequestSchema;
    output: typeof ListContestProblemsResponseSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_spaco_catalog_v1_catalog, 0);
