// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package accountsqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, time_zone)
VALUES ($1, $2)
`

type CreateAccountParams struct {
	ID       uuid.UUID
	TimeZone string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.ID, arg.TimeZone)
	return err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :execrows
INSERT INTO auth_identities (issuer, subject, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (issuer, subject) DO NOTHING
`

type CreateAuthIdentityParams struct {
	Issuer  string
	Subject string
	UserID  uuid.UUID
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAuthIdentity, arg.Issuer, arg.Subject, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const findAccountByID = `-- name: FindAccountByID :one
SELECT id, atcoder_id, time_zone
FROM accounts
WHERE id = $1
`

type FindAccountByIDRow struct {
	ID        uuid.UUID
	AtcoderID *string
	TimeZone  string
}

func (q *Queries) FindAccountByID(ctx context.Context, id uuid.UUID) (FindAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountByID, id)
	var i FindAccountByIDRow
	err := row.Scan(&i.ID, &i.AtcoderID, &i.TimeZone)
	return i, err
}

const findUserIDByAuthIdentity = `-- name: FindUserIDByAuthIdentity :one
SELECT user_id
FROM auth_identities
WHERE issuer = $1 AND subject = $2
`

type FindUserIDByAuthIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) FindUserIDByAuthIdentity(ctx context.Context, arg FindUserIDByAuthIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findUserIDByAuthIdentity, arg.Issuer, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE accounts
SET
    atcoder_id = $2,
    time_zone = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, atcoder_id, time_zone
`

type UpdateAccountProfileParams struct {
	ID        uuid.UUID
	AtcoderID *string
	TimeZone  string
}

type UpdateAccountProfileRow struct {
	ID        uuid.UUID
	AtcoderID *string
	TimeZone  string
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (UpdateAccountProfileRow, error) {
	row := q.db.QueryRow(ctx, updateAccountProfile, arg.ID, arg.AtcoderID, arg.TimeZone)
	var i UpdateAccountProfileRow
	err := row.Scan(&i.ID, &i.AtcoderID, &i.TimeZone)
	return i, err
}
