// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountsqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (int64, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	FindAccountByID(ctx context.Context, id uuid.UUID) (FindAccountByIDRow, error)
	FindUserIDByAuthIdentity(ctx context.Context, arg FindUserIDByAuthIdentityParams) (uuid.UUID, error)
	UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (UpdateAccountProfileRow, error)
}

var _ Querier = (*Queries)(nil)
